[general]

live_config_reload = true

[window]

opacity = 0.71
dynamic_padding = true 

[font]

normal = { family = "DejaVu Sans Mono", style = "Regular" }

[cursor]

style = { shape = "Underline", blinking = "On" }
thickness = 0.1

[mouse]

hide_when_typing = true

[colors]

cursor = { cursor = "#096eae" }
draw_bold_text_with_bright_colors = true
